"""Evaluation: reports classifier metrics AND makes an explicit, unavoidable
distinction between "the pipeline ran and produced a scorable model"
(pipeline-valid) and "the model is actually a robust wake-word detector"
(a claim this stage never makes on its own). See report_summary()'s
"caveats" field, which is always populated, never empty, for a dev-scale run.
"""
from __future__ import annotations

import numpy as np


def _scores(net, arr: "np.ndarray") -> "np.ndarray":
    import torch
    if arr.size == 0:
        return np.array([], dtype=np.float32)
    with torch.no_grad():
        return net(torch.from_numpy(arr)).squeeze(-1).numpy()


def evaluate_model(config: dict, owwmodel, features_val: dict[str, "np.ndarray"],
                   clip_seconds: float) -> dict:
    net = owwmodel.model
    net.eval()
    threshold = config["evaluation"]["threshold"]

    positive = features_val.get("positive_val", np.zeros((0, 0, 0), dtype=np.float32))
    negative_keys = [k for k in features_val if not k.startswith("positive")]
    neg_arrays = [features_val[k] for k in negative_keys if features_val[k].size]
    negative = (np.concatenate(neg_arrays, axis=0) if neg_arrays
               else np.zeros((0, 0, 0), dtype=np.float32))

    pos_scores = _scores(net, positive)
    neg_scores = _scores(net, negative)

    n_pos, n_neg = len(pos_scores), len(neg_scores)
    true_positives = int((pos_scores >= threshold).sum()) if n_pos else 0
    false_negatives = int((pos_scores < threshold).sum()) if n_pos else 0
    false_positives = int((neg_scores >= threshold).sum()) if n_neg else 0
    true_negatives = int((neg_scores < threshold).sum()) if n_neg else 0

    recall = true_positives / n_pos if n_pos else None
    false_reject_rate = false_negatives / n_pos if n_pos else None
    false_accept_rate = false_positives / n_neg if n_neg else None
    accuracy = ((true_positives + true_negatives) / (n_pos + n_neg)
               if (n_pos + n_neg) else None)

    negative_hours = (n_neg * clip_seconds) / 3600.0
    fp_per_hour = false_positives / negative_hours if negative_hours > 0 else None

    threshold_sweep = []
    for t in (0.1, 0.3, 0.5, 0.7, 0.9):
        threshold_sweep.append({
            "threshold": t,
            "false_negatives": int((pos_scores < t).sum()) if n_pos else None,
            "false_positives": int((neg_scores >= t).sum()) if n_neg else None,
        })

    caveats = [
        "This evaluation reflects ONLY the synthetic dev-scale validation set "
        "generated by this pipeline run - it is not an independent, "
        "held-out, real-world test.",
    ]
    if n_pos < 20:
        caveats.append(
            f"positive_val has only {n_pos} clips; metrics from this few "
            f"examples are noisy and not statistically meaningful.")
    if n_neg < 20:
        caveats.append(
            f"negative validation has only {n_neg} clips ({negative_hours:.4f} "
            f"hours); the false-positive-rate/hour figure is not meaningful "
            f"at this scale - openwakeword's own pretrained models are "
            f"evaluated against hours of continuous real audio.")
    if negative_hours < 1.0:
        caveats.append(
            f"negative validation covers only ~{negative_hours:.4f} hours of "
            f"audio (clip count alone can look adequate while duration is "
            f"still tiny - {n_neg} short clips here). false_positives_per_hour "
            f"({fp_per_hour}) is extrapolated from a handful of minutes and is "
            f"NOT comparable to openwakeword's own hours-long evaluation "
            f"corpora (e.g. the Dinner Party Corpus) - do not use this figure "
            f"to judge real-world false-accept behavior.")
    caveats.append(
        "PASSING these metrics means the pipeline is pipeline-valid and "
        "inference-valid, NOT that the wake word is production-ready. "
        "See the final report's 'known limitations' for what a real "
        "robustness evaluation would require.")

    return {
        "n_positive_val": n_pos,
        "n_negative_val": n_neg,
        "threshold": threshold,
        "true_positives": true_positives,
        "false_negatives": false_negatives,
        "false_positives": false_positives,
        "true_negatives": true_negatives,
        "recall": recall,
        "false_reject_rate": false_reject_rate,
        "false_accept_rate": false_accept_rate,
        "accuracy": accuracy,
        "negative_hours_tested": negative_hours,
        "false_positives_per_hour": fp_per_hour,
        "target_fp_per_hour": config["evaluation"]["target_fp_per_hour"],
        "threshold_sweep": threshold_sweep,
        "caveats": caveats,
    }


def format_report(metrics: dict) -> str:
    lines = [
        "=== Evaluation report (hey_void) ===",
        f"positive validation clips: {metrics['n_positive_val']}",
        f"negative validation clips: {metrics['n_negative_val']} "
        f"(~{metrics['negative_hours_tested']:.4f} hours)",
        f"threshold: {metrics['threshold']}",
        f"true positives: {metrics['true_positives']}  "
        f"false negatives: {metrics['false_negatives']}",
        f"false positives: {metrics['false_positives']}  "
        f"true negatives: {metrics['true_negatives']}",
        f"recall: {metrics['recall']}",
        f"false-reject rate: {metrics['false_reject_rate']}",
        f"false-accept rate: {metrics['false_accept_rate']}",
        f"accuracy: {metrics['accuracy']}",
        f"false positives/hour: {metrics['false_positives_per_hour']} "
        f"(target: {metrics['target_fp_per_hour']})",
        "threshold sweep:",
    ]
    for row in metrics["threshold_sweep"]:
        lines.append(f"  t={row['threshold']}: FN={row['false_negatives']} "
                     f"FP={row['false_positives']}")
    lines.append("")
    lines.append("CAVEATS:")
    for c in metrics["caveats"]:
        lines.append(f"  - {c}")
    return "\n".join(lines)
